# Generated by Django 4.2.3 on 2023-07-26 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jhpl_ims", "0011_alter_jhpl_ims_masterlist_approved_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="incident",
            fields=[
                ("incident_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("incident_datetime", models.DateTimeField()),
                ("people_involved", models.TextField()),
                ("incident_location", models.CharField(max_length=200)),
                ("incident_description", models.TextField()),
                (
                    "incident_witness",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("picture", models.BinaryField(blank=True, editable=True, null=True)),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="The MIMEType of the file",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
