# Generated by Django 4.2.3 on 2023-07-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jhpl_ims", "0012_incident"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="incident_outcome",
            field=models.BooleanField(default=False),
        ),
    ]
